// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Cpp_twocomp_iv
NumericMatrix Cpp_twocomp_iv(NumericVector cl, NumericVector v1, NumericVector v2, NumericVector q, NumericVector ti);
RcppExport SEXP _twocompiv_Cpp_twocomp_iv(SEXP clSEXP, SEXP v1SEXP, SEXP v2SEXP, SEXP qSEXP, SEXP tiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cl(clSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ti(tiSEXP);
    rcpp_result_gen = Rcpp::wrap(Cpp_twocomp_iv(cl, v1, v2, q, ti));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_twocompiv_Cpp_twocomp_iv", (DL_FUNC) &_twocompiv_Cpp_twocomp_iv, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_twocompiv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
