# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cpp_twocomp_iv <- function(cl, v1, v2, q, ti) {
    .Call(`_twocompiv_Cpp_twocomp_iv`, cl, v1, v2, q, ti)
}

